<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'CmsCldrCalendar\Holiday'                                  => __DIR__ . '/src/Holiday.php',
    'CmsCldrCalendar\HolidayInterface'                         => __DIR__ . '/src/HolidayInterface.php',
    'CmsCldrCalendar\HolidayRuleInterface'                     => __DIR__ . '/src/HolidayRuleInterface.php',
    'CmsCldrCalendar\Mapping\CalendarableInterface'            => __DIR__ . '/src/Mapping/CalendarableInterface.php',
    'CmsCldrCalendar\Mapping\CalendarInterface'                => __DIR__ . '/src/Mapping/CalendarInterface.php',
    'CmsCldrCalendar\Mapping\HolidayRule\FixedInterface'       => __DIR__ . '/src/Mapping/HolidayRule/FixedInterface.php',
    'CmsCldrCalendar\Mapping\HolidayRule\MoveableInterface'    => __DIR__ . '/src/Mapping/HolidayRule/MoveableInterface.php',
    'CmsCldrCalendar\Mapping\HolidayRule\RelatedInterface'     => __DIR__ . '/src/Mapping/HolidayRule/RelatedInterface.php',
    'CmsCldrCalendar\Mapping\HolidayRule\TransferredInterface' => __DIR__ . '/src/Mapping/HolidayRule/TransferredInterface.php',
    'CmsCldrCalendar\Mapping\HolidayRuleInterface'             => __DIR__ . '/src/Mapping/HolidayRuleInterface.php',
    'CmsCldrCalendar\Mapping\Traits\CalendarableTrait'         => __DIR__ . '/src/Mapping/Traits/CalendarableTrait.php',
    'CmsCldrCalendar\Module'                                   => __DIR__ . '/src/Module.php',
    'CmsCldrCalendar\Stdlib\CalendarUtils'                     => __DIR__ . '/src/Stdlib/CalendarUtils.php',
    'CmsCldrCalendar\TransferredRuleInterface'                 => __DIR__ . '/src/TransferredRuleInterface.php',
);
